---
title: "Intangible capital"
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{Intangible capital}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  message=FALSE, 
  echo=FALSE, 
  warning=FALSE
)

```

```{r setup}
library(pRoductivity)
devtools::load_all()

library(tidyverse)
library(ggptt)
library(pttdatahaku)

set_ptt()

geo_intan <- c("BE", "DK", "DE", "ES", "FR", "IT", "NL", "AT", "FI", "SE", "UK", "NO", "US")
geo_ea7 <- c("BE", "DE", "ES", "FR", "IT", "NL", "AT")

var_intans <- c("EconComp", "Innovprop", "OrgCap", "RD", "Soft_DB", "Brand", "Design", "NFP", "OIPP", "Train")
var_agg <- c("Intang", "NatAcc", "NonNatAcc", "Tang", "TangNRes")

```

## Investment ratio

Aineettomat ja aineelliset suhteessa BKT:seen

Koko taloudessa aineettomien investointiaste 

```{r, fig.height=10, fig.width=8}

data_luiss_intan_groups |> 
  filter_recode(
    geo = c("FI", "SE", "US", geo_ea7),
    nace0 = c("total", "private", "manu", "service"),
    vars = c("I_Intang", "I_Tang", "VAadj")
  ) |> 
  mutate(geo = fct_other(geo, drop = geo_ea7, other_level = "EA 7")) |> 
  group_by(geo, nace0, vars, time) |> 
  summarise(values = sum(values)) |> 
  group_by(geo, nace0, time) |> 
  mutate(values = 100 * values /values[vars == "VAadj"]) |> 
  ungroup() |> 
  filter(vars != "VAadj") |> 
  ggplot(aes(time, values, colour = geo)) +
  facet_grid(nace0~vars) +
  geom_line() +
  # scale_linewidth_discrete(range = c(2,1)) +
  the_title_blank("xl") +
  labs(y = "%")

```


Aineettomat, viisi suurinta

```{r, fig.height=10, fig.width=8}

data_luiss_intan_groups |> 
  filter_recode(
    geo = c("FI", "SE", "US", geo_ea7),
    nace0 = c("total", "private", "manu", "service"),
    vars = c(paste0("I_", var_intans[1:5]), "VAadj")
  ) |> 
  mutate(geo = fct_other(geo, drop = geo_ea7, other_level = "EA 7")) |> 
  group_by(geo, nace0, vars, time) |> 
  summarise(values = sum(values)) |> 
  group_by(geo, nace0, time) |> 
  mutate(values = 100 * values /values[vars == "VAadj"]) |> 
  ungroup() |> 
  filter(vars != "VAadj") |> 
  ggplot(aes(time, values, colour = geo)) +
  geom_line() +
  facet_grid(nace0~vars) +
  geom_h0() +
  the_title_blank("xl") +
  labs(y = "%")

```

Aineettomat, loput

```{r, fig.height=10, fig.width=8}

data_luiss_intan_groups |> 
  filter_recode(
    geo = c("FI", "SE", "US", geo_ea7),
    nace0 = c("total", "private", "manu", "service"),
    vars = c(paste0("I_", var_intans[6:10]), "VAadj")
  ) |> 
  mutate(geo = fct_other(geo, drop = geo_ea7, other_level = "EA 7")) |> 
  group_by(geo, nace0, vars, time) |> 
  summarise(values = sum(values)) |> 
  group_by(geo, nace0, time) |> 
  mutate(values = 100 * values /values[vars == "VAadj"]) |> 
  ungroup() |> 
  filter(vars != "VAadj") |> 
  ggplot(aes(time, values, colour = geo)) +
  geom_line() +
  facet_grid(nace0~vars) +
  geom_h0() +
  the_title_blank("xl") +
  labs(y = "%")

```

## Capital stock

Aineettomat ja aineelliset suhteessa BKT:seen

```{r, fig.height=10, fig.width=8}

data_luiss_intan_groups |> 
  filter_recode(
    geo = c("FI", "SE", "US", geo_ea7),
    nace0 = c("total", "private", "manu", "service"),
    vars = c("K_Intang", "K_Tang", "VAadj")
  ) |> 
  mutate(geo = fct_other(geo, drop = geo_ea7, other_level = "EA 7")) |> 
  group_by(geo, nace0, vars, time) |> 
  summarise(values = sum(values)) |> 
  group_by(geo, nace0,  time) |> 
  mutate(values = 100 * values /values[vars == "VAadj"]) |> 
  ungroup() |> 
  filter(vars != "VAadj") |> 
  ggplot(aes(time, values, colour = geo)) +
  geom_line() +
  facet_grid(nace0~vars, scales = "free") +
  scale_linewidth_discrete(range = c(2,1)) +
  the_title_blank("xl") +
  labs(y = "%")

```
