---
title: "Päätoimialat"
author: "Janne Huovari"
date: "`r Sys.Date()`"
output: rmarkdown::html_document

---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  fig.path = "fig_intro/",
  fig.width = 10,
  fig.height = 8,
  collapse = TRUE,
  comment = "#>"
)


library(tidyverse)
library(glue)
library(ggptt)
library(patchwork)

devtools::load_all()
# set_ptt()



set_gg(theme_ptt(), ptt_pal)

# Data

data("data_main", "data_main_groups", "ssca_lp_ind10", "ssca_lp_ind", "scca_exp")


high_country <- "Suomi"
high_countries <- c("Ruotsi", "Euroalue-12", "Saksa", "Yhdysvallat", "Tanska")


```


```{r lp}

data_main_groups %>% 
  ggplot(aes(time, lp_ind, colour = geo)) +
  facet_wrap(~ nace0) +
  geom_line() 

```

# Yksityinen sektori

```{r lp_private_high}

data_main_groups %>% 
  filter(nace0 == "private") %>% 
  prod_ind_plot_high()

ssca_plot("Yksityinen sektori, 2008 = 100", ssca_obj = filter(ssca_lp_ind, nace0 == "private")[["ssca_obj_08"]][[1]])
ssca_plot("Yksityinen sektori, 2010 = 100", ssca_obj = filter(ssca_lp_ind10, nace0 == "private")[["ssca_obj_10"]][[1]])
  
```

# Yksityinen ilman 26

```{r lp_private_ex26_high}

data_main_groups %>% 
  filter(nace0 == "private_ex26") %>% 
  prod_ind_plot_high()

ssca_plot("Yksityinen sektori ilman 26, 2008 = 100", ssca_obj = filter(ssca_lp_ind, nace0 == "private_ex26")[["ssca_obj_08"]][[1]])


```

# Teollisuus

```{r lp_manu}

p1_manu <- data_main_groups %>% 
  filter(nace0 == "manu", time >= 2000) %>% 
  prod_ind_plot_high() +
  ggtitle("a. Suomi ja vertailumaat") +
  theme(plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "cm"))

# ssca_plot("Teollisuus, 2008 = 100", ssca_obj = filter(ssca_lp_ind, nace0 == "manu")[["ssca_obj_08"]][[1]])
# ssca_plot("Teollisuus, 2010 = 100", ssca_obj = filter(ssca_lp_ind10, nace0 == "manu")[["ssca_obj_10"]][[1]])

ssca_pdata <- ssca_plot_data(filter(ssca_lp_ind, nace0 == "manu")[["ssca_obj_08"]][[1]]) %>% 
  filter(year >= 2000)
  
p3_manu <- ssca_pdata %>% 
  ssca_plot_diff() 

p2_manu <- ssca_pdata %>% 
  ssca_plot_level() 

p1_manu / ((p2_manu | p3_manu) + plot_layout(guides = "collect")) + plot_layout(heights = c(3, 2))

ggsave(here::here("figures/manu.pdf"), width = 10, height = 8)
ggsave(here::here("figures/manu.svg"), width = 10, height = 8)
ggsave(here::here("figures/manu.png"), width = 10, height = 8)
ggsave(here::here("figures/manu.eps"), width = 10, height = 8)
ggsave(here::here("figures/manu.ps"), width = 10, height = 8)
ggsave(here::here("figures/manu.wmf"), width = 10, height = 8)

```

# Teollisuus ilman 26

```{r lp_manu_ex_high}

data_main_groups %>% 
  filter(nace0 == "manu_ex26") %>% 
  prod_ind_plot_high()

ssca_plot("Teollisuus ilman 26, 2008 = 100", ssca_obj = filter(ssca_lp_ind, nace0 == "manu_ex26")[["ssca_obj_08"]][[1]])
ssca_plot("Teollisuus, 2010 = 100", ssca_obj = filter(ssca_lp_ind10, nace0 == "manu_ex26")[["ssca_obj_10"]][[1]])
  
```

# Palvelut

```{r lp_serv_high}

data_main_groups %>% 
  filter(nace0 == "service") %>% 
  prod_ind_plot_high()

ssca_plot("Palvelut, 2008 = 100", ssca_obj = filter(ssca_lp_ind, nace0 == "service")[["ssca_obj_08"]][[1]])
ssca_plot("Palvelut, 2010 = 100", ssca_obj = filter(ssca_lp_ind10, nace0 == "service")[["ssca_obj_10"]][[1]])
  
```

# Vienti

```{r export}

scca_exp$p6_ind$z_list$theCall$longdata %>% 
  mutate(lp_ind = p6_ind) %>% 
  prod_ind_plot_high()

ssca_plot("Vienti", ssca_obj = scca_exp$p6_ind)

```

# Tavaroiden vienti

```{r export_g}

scca_exp$p61_ind$z_list$theCall$longdata %>% 
  mutate(lp_ind = p61_ind) %>% 
  prod_ind_plot_high()

ssca_plot("Tavaroiden vienti", ssca_obj = scca_exp$p61_ind)

```

# Palveluiden vienti

```{r export_s}

scca_exp$p62_ind$z_list$theCall$longdata %>% 
  mutate(lp_ind = p62_ind) %>% 
  prod_ind_plot_high()

ssca_plot("Palveluiden vienti", ssca_obj = scca_exp$p62_ind)

```
