---
title: "Raportin luvun 3 kuviot"
author: "Janne Huovari"
date: "`r Sys.Date()`"
output: rmarkdown::html_document

---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  fig.path = "fig_report/",
  fig.width = 10,
  fig.height = 8,
  collapse = TRUE,
  comment = "#>", 
  echo = FALSE, 
  comment = FALSE, 
  warning = FALSE
)


library(tidyverse)
library(glue)
library(ggptt)
library(patchwork)
library(ficomp)
library(gt)
library(tidyselect)

devtools::load_all()

set_board_theme(base_size = 10)

# Data




dat_kuviot <- 
  readxl::read_xlsx(
    path = here::here("data-raw/Kuviot.xlsx")
  ) %>% 
  mutate(time = as.numeric(time)) %>% 
  gather(vars, values, -time)

file_kuviot_johd <- here::here("data-raw/Johdanto-kuvioiden_data_v2.xlsx")

dat_kuviot_johd <- 
  set_names(readxl::excel_sheets(file_kuviot_johd)) %>% 
  map(~readxl::read_xlsx(file_kuviot_johd, sheet = .x))  

file_kuviot_3 <- here::here("data-raw/luku_3_kuviot_v2.xlsx")

dat_kuviot_3 <- 
  set_names(setdiff(readxl::excel_sheets(file_kuviot_3), c("3.1", "3.2", "3.3", "3.4", "3.7", "3.8"))) %>% 
  map(~readxl::read_xlsx(file_kuviot_3, sheet = .x))  

high_country <- "Suomi"

fig_height <- 10

# plot_start_year <- 2000

```

```{r}

dat_oecd_levels %>% 
  prod_ind_plot_high(plot_var = "gdp_per_h", high_country = "Suomi", high_countries = setdiff(unique(.$geo_name), high_country), base_year = 2015) +
  the_legend_bot() +
  geom_h0() +
  labs(y = "Vuoden 2015 hinnoin, $, ostovoimakorjattu",
       caption = "Lähde: OECD") 


save_figs("Kuvio_1_1", height = fig_height)


```

```{r}



dat_oecd_levels %>% 
  group_by(time) %>% 
  mutate(rel_ch = 100 * gdp_per_h / gdp_per_h[geo == "CH"]) %>% 
  ungroup() %>% 
  prod_ind_plot_high(plot_var = "rel_ch", high_country = "Suomi", high_countries = setdiff(unique(.$geo_name), high_country), base_year = 2015) +
  the_legend_bot() +
  # geom_h0() +
  labs(y = "Indeksi, Sveitsi = 100",
       caption = "Lähde: OECD") 


save_figs("Kuvio_1_2", height = fig_height)


```


```{r}

dat_kuviot_johd[["1.3"]] %>% 
  gather(geo, values, -vuosi, -otsikko, -otsikko_en) %>% 
  mutate(geo_name = geo,
         time = vuosi) %>% 
  prod_ind_plot_high(plot_var = "values", high_country = "Suomi", high_countries = setdiff(unique(.$geo_name), high_country), base_year = 1997) +
  the_legend_bot() 

save_figs("Kuvio_1_3", height = fig_height)

```

```{r}

dat_kuviot_johd[["1.4"]] %>% 
  gather(geo, values, -vuosi, -otsikko, -otsikko_en) %>% 
  mutate(geo_name = geo,
         time = vuosi) %>% 
  prod_ind_plot_high(plot_var = "values", high_country = "Suomi", high_countries = setdiff(unique(.$geo_name), high_country), base_year = 2007) +
  the_legend_bot() 

save_figs("Kuvio_1_4", height = fig_height)

```

```{r}

dat_kuviot_johd[c("1.5A", "1.5B", "1.5C")] %>% #str() # names()
  bind_rows() %>% 
  mutate(period = stringr::str_extract(otsikko, "20.*")) %>% 
  mutate(geo = fct_reorder(Maa, keskiarvo)) %>% 
  ggplot(aes(geo, keskiarvo)) +
  facet_wrap(~period) +
  geom_col(fill = tula_pal(1)) +
  coord_flip() +
  the_title_blank(c("x", "y"))


save_figs("Kuvio_1_5", height = fig_height +2)

```
```{r}

dat_kuviot_johd[c("1.6A", "1.6B", "1.6C")] %>% #str() # names()
  bind_rows() %>% 
  mutate(period = stringr::str_extract(otsikko, "20.*")) %>% 
  mutate(geo = fct_reorder(Maa, keskiarvo)) %>% 
  ggplot(aes(geo, keskiarvo)) +
  facet_wrap(~period) +
  geom_col(fill = tula_pal(1)) +
  coord_flip() +
  the_title_blank(c("x", "y"))


save_figs("Kuvio_1_6", height = fig_height +2)

```


```{r}

dat_kuviot_johd[["1.7"]] %>% # names()
  select(-contains("index")) %>%
  gather(geo, values, -vuosi, -otsikko, -viittaus) %>% 
  mutate(geo_name = geo,
         time = vuosi,
         lp_ind = values) %>% 
  prod_ind_plot_high(plot_var = "values", high_country = "Suomi", high_countries = setdiff(unique(.$geo_name), high_country), base_year = 1995) +
  geom_hline(yintercept = 100) +
  the_legend_bot() 

save_figs("Kuvio_1_7", height = fig_height)

```
```{r}

dat_kuviot_johd[["1.8"]] %>%  #names()
  select(-contains("ind")) %>%
  gather(geo, values, -vuosi, -Otsikko_fi, -viittaus) %>% 
  mutate(geo_name = geo,
         time = vuosi) %>% 
  prod_ind_plot_high(plot_var = "values", high_country = "Suomi", high_countries = setdiff(unique(.$geo_name), high_country), base_year = 2008) +
  geom_hline(yintercept = 100) +
  scale_size_manual(values = c(1.5), guide = "none") +
  ylim(c(0,120)) +
  the_legend_bot() 

save_figs("Kuvio_1_8", height = fig_height)

```

```{r}

dat_kuviot_johd[["1.9"]] %>% #names()
  gather(geo, values, -vuosi, -otsikko_fi, -otsikko_en) %>% 
  mutate(geo_name = geo,
         time = vuosi) %>% 
  ggplot(aes(time, values, colour = geo_name)) + 
  geom_line() +
  scale_colour_manual(values = rev(tula_pal(2))) +
  the_legend_bot() +
  the_title_blank(c("x", "l")) +
  labs(y = "indeksi, 1992 = 100")

save_figs("Kuvio_1_9", height = fig_height)

```

```{r}

dat_kuviot_johd[["1.10"]] %>% # names()
  gather(geo, values, -vuosi, -otsikko, -viittaus) %>% 
  mutate(geo_name = geo,
         time = vuosi) %>% 
  prod_ind_plot_high(plot_var = "values", high_country = "Suomi", high_countries = setdiff(unique(.$geo_name), high_country), base_year = 2002) +
  the_legend_bot() +
  scale_x_datetime() +
  geom_hline(yintercept = 0) +
  labs(y = "%")

save_figs("Kuvio_1_10", height = fig_height)

```

```{r}

dat_kuviot_johd[["1.11"]] %>% # names()
  gather(geo, values, -vuosi, -otsikko, -viittaus) %>% 
  mutate(geo_name = geo,
         time = vuosi) %>% 
  prod_ind_plot_high(plot_var = "values", high_country = "Suomi", high_countries = setdiff(unique(.$geo_name), high_country), base_year = 2002) +
  the_legend_bot() +
  scale_x_datetime() +
  geom_hline(yintercept = 0) +
  labs(y = "%")

save_figs("Kuvio_1_11", height = fig_height)

```
```{r}

dat_kuviot_johd[["1.12"]] %>% # names()
  gather(geo, values, -vuosi, -otsikko) %>% 
  mutate(geo_name = geo,
         time = vuosi) %>% 
    rename(plot_var = values) %>%
  mutate(high_names = geo_name,
         high_names = fct_relevel(high_names, c("Suomi", "Maailman tuonti"), after = 0),
         high_size = fct_other(high_names, keep = c("Suomi", "Maailman tuonti"), other_level = "muut high"),
         geo_name = fct_relevel(geo_name, c(high_countries, high_country), after = Inf)) %>%
    ggplot(aes(time, plot_var, group = geo_name, colour = high_names, size = high_size)) +
    # geom_line(alpha = 0.7) +
    geom_line() +
    scale_size_manual(values = c(2.5, 2, 1), guide = "none") +
    # scale_colour_manual(values = tula_pal) +
    guides(colour = guide_legend()) +
    the_title_blank(c("x", "l")) +
    labs(y = glue("Indeksi, {base_year} = 100")) +
  the_legend_bot() +
  geom_hline(yintercept = 100) +
  labs(y = "%") +
  ylim(c(25,175))

save_figs("Kuvio_1_12", height = fig_height)

```


```{r}

dat_kuviot_johd[["1.13"]] %>% # names()
  mutate(across(contains("reaaliset"), ~(.x * -2))) %>% 
  rename(time = Vuosi) %>% 
  gather(vars, values, -time) %>% 
  ggplot(aes(time, values, colour = vars)) +
  geom_line() +
  scale_y_continuous(sec.axis = sec_axis(~ . * -0.5)) +
  guides(colour = guide_legend(nrow = 2)) +
  geom_h0() +
  the_legend_bot() +
  the_title_blank(c("x", "l")) +
  labs(y = "Poikkeama trendistä, %",
       caption = "Lähde: AMECO, Tuottavuuslautakunta") 

save_figs("Kuvio_1_13", height = fig_height)
```


```{r}

dat_kuviot_johd[["1.14"]] %>% # names()
  mutate(across(contains("reaaliset"), ~(.x * -1))) %>% 
  rename(time = Vuosi) %>% 
  gather(vars, values, -time) %>% 
  ggplot(aes(time, values, colour = vars)) +
  geom_line() +
  scale_y_continuous(sec.axis = sec_axis(~ . * -1)) +
  guides(colour = guide_legend(nrow = 2)) +
  geom_h0() +
  the_legend_bot() +
  the_title_blank(c("x", "l")) +
  labs(y = "Poikkeama trendistä, %",
       caption = "Lähde: AMECO, Tuottavuuslautakunta") 

save_figs("Kuvio_1_14", height = fig_height)

```


```{r}

dat_kuviot_johd[["1.15"]] %>% # names()
  mutate(across(contains("reaaliset"), ~(.x * -1))) %>% 
  rename(time = Vuosi) %>% 
  gather(vars, values, -time) %>% 
  mutate(vars = fct_rev(vars)) %>% 
  ggplot(aes(time, values, colour = vars)) +
  geom_line() +
  scale_y_continuous(sec.axis = sec_axis(~ . * -1)) +
  guides(colour = guide_legend(nrow = 2)) +
  geom_h0() +
  the_legend_bot() +
  the_title_blank(c("x", "l")) +
  labs(y = "Poikkeama trendistä, %",
       caption = "Lähde: AMECO, Tuottavuuslautakunta") 

save_figs("Kuvio_1_15", height = fig_height)

```

```{r}

dat_kuviot_johd[["1.16"]] %>% # names()
  mutate(across(contains("reaaliset"), ~(.x * -2))) %>% 
  rename(time = Vuosi) %>% 
  gather(vars, values, -time) %>% 
  ggplot(aes(time, values, colour = vars)) +
  geom_line() +
  scale_y_continuous(sec.axis = sec_axis(~ . * -0.5)) +
  guides(colour = guide_legend(nrow = 2)) +
  geom_h0() +
  the_legend_bot() +
  the_title_blank(c("x", "l")) +
  labs(y = "Poikkeama trendistä, %",
       caption = "Lähde: AMECO, Tuottavuuslautakunta") 

save_figs("Kuvio_1_16", height = fig_height)

```


```{r}

dat_kuviot_johd[["1.17"]] %>% # names()
  mutate(across(contains("reaaliset"), ~(.x * -10))) %>% 
  rename(time = Vuosi) %>% 
  gather(vars, values, -time) %>% 
  ggplot(aes(time, values, colour = vars)) +
  geom_line() +
  scale_y_continuous(sec.axis = sec_axis(~ . * -1/10)) +
  guides(colour = guide_legend(nrow = 2)) +
  geom_h0() +
  the_legend_bot() +
  the_title_blank(c("x", "l")) +
  labs(y = "Poikkeama trendistä, %",
       caption = "Lähde: AMECO, Tuottavuuslautakunta") 

save_figs("Kuvio_1_17", height = fig_height)

```



```{r}

dat_kuviot_3[c("3.4A", "3.4B")] %>% #str() # names()
  bind_rows() %>% 
  rename(time = Vuosi,
         '"Kirnuaminen (oik)"' = '"Kirnuaminen"') %>% 
  mutate(across(contains("Kirnuaminen"), ~(.x - 0.25))) %>% 
  gather(vars, values, -time, -Toimiala) %>% 
  ggplot(aes(time, values, colour = vars)) +
  facet_wrap(~Toimiala) + #, scales = "free"
  geom_line() +
  scale_y_continuous(sec.axis = sec_axis(~ . + 0.25)) +
  the_title_blank(c("x", "y", "l")) +
  the_legend_bot() +
  geom_hline(yintercept = 0)

save_figs("Kuvio_3_4", height = fig_height)

```

```{r}

dat_kuviot_3[["3.5"]] %>% # str() # names()
  gather(time, values, -maa_en, -maa_koodi, -indikaattori, -maa_fi) %>% 
  mutate(time = as.numeric(time),
         lp_ind = values,
         geo_name = maa_fi) %>%
  mutate(geo_name = fct_rev(fct_relevel(geo_name, high_country, after = Inf))) %>% # pull(maa_fi) %>% levels()
  # mutate(geo_name = fct_relevel(geo_name, high_country, after = Inf)) %>%
  # ggplot(aes(time, values, colour = geo_name)) +
  # geom_line()
  prod_ind_plot() +
  guides(colour = guide_legend()) +
  labs(y = "%") +
  geom_hline(yintercept = 0) +
  the_legend_bot()

save_figs("Kuvio_3_5", height = fig_height)

```

```{r}


dat_kuviot_3[["3.6"]] %>%
  rename(time = Vuosi) %>% 
  gather(vars, values, -time) %>% 
  mutate(time = as.numeric(time)) %>% 
  ggplot(aes(time, values, fill = vars)) +
  geom_area() +
  the_title_blank(c("x", "l")) +
  the_legend_bot() +
  geom_hline(yintercept = 0) +
  labs(y = "%")

save_figs("Kuvio_3_6", height = fig_height)
```

```{r}

dat_kuviot_3[c("3.7A", "3.7B")] %>% #str() # names()
  bind_rows() %>% 
  rename(time = Vuosi) %>% 
  # mutate(across(contains("Kirnuaminen"), ~(.x - 0.25))) %>% 
  gather(geo_name, values, -time, -Toimiala) %>% 
  mutate(lp_ind = values) %>%
  mutate(geo_name = fct_rev(fct_relevel(geo_name, high_country, after = Inf))) %>% 
  prod_ind_plot() +
  # ggplot(aes(time, values, colour = vars)) +
  facet_wrap(~Toimiala) + 
  geom_line() +
  guides(colour = guide_legend()) +
  # scale_y_continuous(sec.axis = sec_axis(~ . + 0.25)) +
  the_title_blank(c("x", "y", "l")) +
  the_legend_bot() +
  geom_hline(yintercept = 0)

save_figs("Kuvio_3_7", height = fig_height)

```

```{r}

dat_kuviot_3[c("3.8A", "3.8B")] %>% #str() # names()
  bind_rows() %>% 
  filter(!is.na(Toimiala)) %>% 
  rename(time = Vuosi) %>% 
  # mutate(across(contains("Kirnuaminen"), ~(.x - 0.25))) %>% 
  gather(geo_name, values, -time, -Toimiala) %>% 
  ggplot(aes(time, values, colour = geo_name)) +
  # ggplot(aes(time, values, colour = vars)) +
  facet_wrap(~Toimiala) + 
  geom_line() +
  guides(colour = guide_legend()) +
  # scale_y_continuous(sec.axis = sec_axis(~ . + 0.25)) +
  the_title_blank(c("x", "y", "l")) +
  the_legend_bot() +
  geom_hline(yintercept = 0)

save_figs("Kuvio_3_8", height = fig_height)

```

