---
title: "SSCA"
author: "Janne Huovari"
date: "8 11 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(here)
library(tidyverse)

devtools::load_all()

# est_periods <- 1996:2007
# eval_periods <- 2008:2016
# all_periods <- c(est_periods, eval_periods)

# data_exp <- readRDS(here::here("data/ssca_data_example.rds"))

data(data_main_groups, data_main10_groups, base_year)

ssca_dat10 <- data_main10_groups %>% 
  complete(nesting(geo, geo_name), nace0, time) %>%
  group_by(geo, nace0) %>% 
  mutate(lp_ind =  100 * lp_ind/lp_ind[time == base_year]) %>% 
  ungroup()

ssca_dat <- data_main_groups %>% 
  complete(nesting(geo, geo_name), nace0, time) %>%
  group_by(geo, nace0) %>% 
  mutate(lp_ind =  100 * lp_ind/lp_ind[time == base_year]) %>% 
  ungroup()

est_periods <- 1996:(base_year - 1)
eval_periods <- base_year:2018
eval_periods10 <- base_year:2019

```

```{r est}

ssca_lp_ind <- 
  ssca_dat %>% 
  nest(data = -nace0) %>%
  mutate(model = map(data, ~ssca_est(.x, unit_var = "geo",
                 target_unit = "FI",
                 value_var = "lp_ind",
                 time_var = "time", 
                 est_periods = est_periods, 
                 eval_periods = eval_periods)),
         model = set_names(model, nace0)) %>% 
  select(-data)

ssca10_lp_ind <- 
  ssca_dat10 %>% 
  nest(data = -nace0) %>% 
  mutate(model = map(data, ~ssca_est(.x, unit_var = "geo",
                 target_unit = "FI",
                 value_var = "lp_ind",
                 time_var = "time", 
                 est_periods = est_periods, 
                 eval_periods = eval_periods10)),
         model = set_names(model, nace0)) %>% 
  select(-data)

usethis::use_data(ssca_lp_ind, ssca10_lp_ind, overwrite = TRUE)

# ssca_lp_ind <- ssca_dat %>% 
#   nest(data = -nace0) %>% 
#   mutate(ssca_obj_08 = map(data, ~ssca_est(.x, unit_var = "geo",
#                  target_unit = "FI",
#                  value_var = "lp_ind",
#                  time_var = "time", est_periods = 1996:2007, eval_periods = 2008:2017)),
#          ssca_obj_10 = map(data, ~ssca_est(.x, unit_var = "geo",
#                  target_unit = "FI",
#                  value_var = "lp_ind",
#                  time_var = "time", est_periods = 1996:2010, eval_periods = 2011:2017)),
#          ssca_obj_11 = map(data, ~ssca_est(.x, unit_var = "geo",
#                  target_unit = "FI",
#                  value_var = "lp_ind",
#                  time_var = "time", est_periods = 1996:2011, eval_periods = 2012:2017)))
  
# ssca_lp_ind10 <- ssca_dat %>% 
#   nest(data = -nace0) %>% 
#   mutate(ssca_obj_08 = map(data, ~ssca_est(.x, unit_var = "geo",
#                  target_unit = "FI",
#                  value_var = "lp_ind10",
#                  time_var = "time", est_periods = 1996:2007, eval_periods = 2008:2017)),
#          ssca_obj_10 = map(data, ~ssca_est(.x, unit_var = "geo",
#                  target_unit = "FI",
#                  value_var = "lp_ind10",
#                  time_var = "time", est_periods = 1996:2010, eval_periods = 2011:2017)),
#          ssca_obj_11 = map(data, ~ssca_est(.x, unit_var = "geo",
#                  target_unit = "FI",
#                  value_var = "lp_ind10",
#                  time_var = "time", est_periods = 1996:2011, eval_periods = 2012:2017)))

# est_periods <- 
#   list(t_08 = list(est_periods = 1996:2007, eval_periods = 2008:2017),
#        t_10 = list(est_periods = 1996:2010, eval_periods = 2011:2017),
#        t_11 = list(est_periods = 1996:2011, eval_periods = 2012:2017))

# ssca_lp_ind10_2 <- ssca_dat %>% 
#   nest(data = -nace0) %>% 
#   mutate(ssca_obj = 
#            map(est_periods, ~map(data, ssca_est, unit_var = "geo",
#                  target_unit = "FI",
#                  value_var = "lp_ind10",
#                  time_var = "time", est_periods = .x$est_periods, eval_periods = .x$eval_periods)))

scca_exp_data <- data_total %>% 
  group_by(geo) %>% 
  mutate(p6_ind = rebase(P6__CLV15_MNAC, time, 2010),
         p61_ind = rebase(P61__CLV15_MNAC, time, 2010),
         p62_ind = rebase(P62__CLV15_MNAC, time, 2010)) 

scca_exp <- map(set_names(c("p6_ind", "p61_ind", "p62_ind")),
                ~ssca_est(scca_exp_data, unit_var = "geo",
                 target_unit = "FI",
                 value_var = .x,
                 time_var = "time", est_periods = 1996:2010, eval_periods = 2011:2017))


usethis::use_data(scca_exp, overwrite = TRUE)


ssca_dat10 %>% 
  filter(nace0 == "private") %>% 
  ggplot(aes(time, geo, fill = is.na(lp_ind))) +
  geom_tile()
  

```


```{r, eval=FALSE, include=FALSE}


######################
### SSCA - Example ###
######################

#Data should be provided in the same format as the example dataset below:

#(1) Long format
#(2) No missing values

data <- readRDS(here("data/ssca_data_example.rds"))


data %>% 
  filter(geo == "FI") %>% 
  mutate(V_FP = statfitools::fp(V_CP, V_PYP, year, 2010),
         LP = V_FP / L) %>% 
  # select(geo, year, LP, d_LP, cvol_LP) %>% 
  gather(vars, values, -geo, -year) %>% 
  ggplot(aes(year, values)) +
  facet_wrap(~ vars, scales = "free") +
  geom_line()



```

```{r demo}
###########################
### Deploying the model ###
###########################




z.list <- data %>% 
  data.frame() %>% 
  z.prep(unit_var = "geo",
                 target_unit = "FI",
                 value_var = "cvol_LP",
                 time_var = "year",
                 intervention = eval_periods[1],
                 first_date = 1996,
                 last_date = eval_periods[length(eval_periods)],
                 start_date = est_periods[1],
                 normalize = "no",
                 drop_countries = c())


#Estimating the model
w.list <- w.opt(z.list)

#Leave-one-out' robustness check
loo.obj <- loo.fun(z.list)


###############
### Results ###
###############

### Country weights ###
W_star <- w.list$W_star
W_star
#OR
round(W_star,2)[which(round(W_star,2) != 0)]

### Normalized RMSE Loss ###
comp.rmse(z.list, W_star)

#############
### Plots ###
#############

z.list$Z0

the_title <- "Yksityinen sektori"

plot.fit(z.list, 
         W_star, 
         start_date = est_periods[1], 
         title = the_title, 
         intervention_date = eval_periods[1]-1,
         LOO = loo.obj, 
         legend_arg = c("Suomi", "Synteettinen kontrolli", "Yksi maa j채tetty pois maajoukosta")
         )

plot.diff(z.list, 
          W_star, 
          intervention = eval_periods[1]-1, 
          title = the_title, 
          history = TRUE, 
          LOO = loo.obj, 
          scale = 32,
          legend_arg = c("Suomi", "Synteettinen kontrolli", "Yksi maa j채tetty pois maajoukosta"))




```

# Yksityinen sektori

```{r private}
###########################
### Deploying the model ###
###########################




private_ssca <- ssca_dat %>% 
  filter(nace0 == "private") %>% 
  ssca_est(unit_var = "geo",
                 target_unit = "FI",
                 value_var = "lp_ind",
                 time_var = "time", est_periods = est_periods, eval_periods = eval_periods)
  


###############
### Results ###
###############

### Country weights ###
private_ssca$w_list$W_star

### Normalized RMSE Loss ###
comp.rmse(private_ssca$z_list, private_ssca$w_list$W_star)

#############
### Plots ###
#############



ssca_plot("Yksityinen sektori", ssca_obj = filter(ssca_lp_ind10, nace0 == "private")[["ssca_obj_08"]][[1]])


```

```{r private_11}

ssca_plot("Yksityinen sektori", ssca_obj = filter(ssca_lp_ind10, nace0 == "private")[["ssca_obj_11"]][[1]])

private_ssca_11 <- ssca_dat %>% 
  filter(nace0 == "private") %>% 
  ssca_est(unit_var = "geo",
                 target_unit = "FI",
                 value_var = "lp_ind",
                 time_var = "time", est_periods = 1996:2010, eval_periods = 2011:2017)
  
ssca_plot("Yksityinen sektori", ssca_obj = private_ssca_11)
```


# Teollisuus

```{r manu}

manu_ssca_08 <- ssca_dat %>% 
  filter(nace0 == "manu") %>% 
  ssca_est(unit_var = "geo",
                 target_unit = "FI",
                 value_var = "lp_ind",
                 time_var = "time", est_periods = 1996:2010, eval_periods = 2011:2017)

manu_ssca_10 <- ssca_dat %>% 
  filter(nace0 == "manu") %>% 
  ssca_est(unit_var = "geo",
                 target_unit = "FI",
                 value_var = "lp_ind10",
                 time_var = "time", est_periods = 1996:2010, eval_periods = 2011:2017)  

ssca_plot("Teollisuus", ssca_obj = manu_ssca_08)
ssca_plot("Teollisuus", ssca_obj = manu_ssca_10)

### Country weights ###
bind_rows(manu_ssca_08$w_list$W_star,
manu_ssca_10$w_list$W_star)

### Normalized RMSE Loss ###
c(comp.rmse(manu_ssca_08$z_list, manu_ssca_08$w_list$W_star),
comp.rmse(manu_ssca_10$z_list, manu_ssca_10$w_list$W_star))

```
 
# Vienti

```{r exp}

exp_ssca_data <- data_total %>% 
  group_by(geo) %>% 
  mutate(p6_ind = rebase(P6__CLV15_MNAC, time, 2010),
         p61_ind = rebase(P61__CLV15_MNAC, time, 2010),
         p62_ind = rebase(P62__CLV15_MNAC, time, 2010)) 

exp_ssca <- exp_ssca_data %>% 
  ssca_est(unit_var = "geo",
                 target_unit = "FI",
                 value_var = "p6_ind",
                 time_var = "time", est_periods = 1996:2010, eval_periods = 2011:2017)
  
ssca_plot("Vienti", ssca_obj = exp_ssca)

```

```{r exp_g}


exp_g_ssca <- exp_ssca_data %>% 
  ssca_est(unit_var = "geo",
                 target_unit = "FI",
                 value_var = "p61_ind",
                 time_var = "time", est_periods = 1996:2010, eval_periods = 2011:2017)
  
ssca_plot("Tavaroiden vienti", ssca_obj = exp_g_ssca)

``` 

```{r exp_s}


exp_s_ssca <- exp_ssca_data %>% 
  ssca_est(unit_var = "geo",
                 target_unit = "FI",
                 value_var = "p62_ind",
                 time_var = "time", est_periods = 1996:2010, eval_periods = 2011:2017)
  
ssca_plot("Palveluiden vienti", ssca_obj = exp_s_ssca)

``` 

# Palvelut

```{r service}
###########################
### Deploying the model ###
###########################

z.list <- ssca_dat %>% 
  filter(nace0 == "service") %>% 
  data.frame() %>% 
  z.prep(unit_var = "geo",
                 target_unit = "FI",
                 value_var = "lp_ind",
                 time_var = "time",
                 intervention = eval_periods[1],
                 first_date = 1996,
                 last_date = eval_periods[length(eval_periods)],
                 start_date = est_periods[1],
                 normalize = "no",
                 drop_countries = c())


#Estimating the model
w.list <- w.opt(z.list)

#Leave-one-out' robustness check
loo.obj <- loo.fun(z.list)


###############
### Results ###
###############

### Country weights ###
W_star <- w.list$W_star
W_star
#OR
round(W_star,2)[which(round(W_star,2) != 0)]

### Normalized RMSE Loss ###
comp.rmse(z.list, W_star)

#############
### Plots ###
#############

the_title <- "Palvelut"

plot.fit(z.list, 
         W_star, 
         start_date = est_periods[1], 
         title = the_title, 
         intervention_date = eval_periods[1]-1,
         LOO = loo.obj, 
         legend_arg = c("Suomi", "Synteettinen kontrolli", "Yksi maa j채tetty pois maajoukosta")
         )

plot.diff(z.list, 
          W_star, 
          intervention = eval_periods[1]-1, 
          title = the_title, 
          history = TRUE, 
          LOO = loo.obj, 
          scale = 32,
          legend_arg = c("Suomi", "Synteettinen kontrolli", "Yksi maa j채tetty pois maajoukosta"))

```
