---
title: "SCCA_old_demo"

---



```{r, eval=FALSE, include=FALSE}


######################
### SSCA - Example ###
######################

#Data should be provided in the same format as the example dataset below:

#(1) Long format
#(2) No missing values

data_exp <- readRDS(here("data/ssca_data_example.rds"))


data_exp %>% 
  filter(geo == "FI") %>% 
  mutate(V_FP = statfitools::fp(V_CP, V_PYP, year, 2010),
         LP = V_FP / L) %>% 
  # select(geo, year, LP, d_LP, cvol_LP) %>% 
  gather(vars, values, -geo, -year) %>% 
  ggplot(aes(year, values)) +
  facet_wrap(~ vars, scales = "free") +
  geom_line()

ssca_exp <- 
  data_exp %>% 
  mutate(nace0 = "total") %>% 
  nest(data = -nace0) %>% 
  mutate(model = map(data, ~ssca_est(.x, unit_var = "geo",
                 target_unit = "FI",
                 value_var = "cvol_LP",
                 time_var = "year", 
                 est_periods = 1996:2007, 
                 eval_periods = 2008:2016)),
         model = set_names(model, nace0)) %>% 
  select(-data)

ssca_exp <- 
  data_exp %>% 
  ssca_est(unit_var = "geo",
                 target_unit = "FI",
                 value_var = "cvol_LP",
                 time_var = "year", 
                 est_periods = 1996:2007, 
                 eval_periods = 2008:2016)

```

```{r demo}
###########################
### Deploying the model ###
###########################

est_periods <- 1996:2007
eval_periods <- 2008:2016
all_periods <- c(est_periods, eval_periods)

  z.list <- data_exp %>%
    data.frame() %>%
    z.prep(unit_var = unit_var,
           target_unit = target_unit,
           value_var = value_var,
           time_var = "time",
           intervention = eval_periods[1],
           first_date = est_periods[1],
           last_date = eval_periods[length(eval_periods)],
           start_date = est_periods[1],
           normalize = "no",
           drop_countries = c())

z.list <- data_exp %>% 
  data.frame() %>% 
  z.prep(unit_var = "geo",
                 target_unit = "FI",
                 value_var = "cvol_LP",
                 time_var = "year",
                 intervention = eval_periods[1],
                 first_date = 1996,
                 last_date = eval_periods[length(eval_periods)],
                 start_date = est_periods[1],
                 normalize = "no",
                 drop_countries = c())


#Estimating the model
w.list <- w.opt(z.list)

#Leave-one-out' robustness check
loo.obj <- loo.fun(z.list)


###############
### Results ###
###############

### Country weights ###
W_star <- w.list$W_star
W_star
#OR
round(W_star,2)[which(round(W_star,2) != 0)]

### Normalized RMSE Loss ###
comp.rmse(z.list, W_star)

#############
### Plots ###
#############

z.list$Z0

the_title <- "Yksityinen sektori"

plot.fit(z.list, 
         W_star, 
         start_date = est_periods[1], 
         title = the_title, 
         intervention_date = eval_periods[1]-1,
         LOO = loo.obj, 
         legend_arg = c("Suomi", "Synteettinen kontrolli", "Yksi maa jätetty pois maajoukosta")
         )

plot.diff(z.list, 
          W_star, 
          intervention = eval_periods[1]-1, 
          title = the_title, 
          history = TRUE, 
          LOO = loo.obj, 
          scale = 32,
          legend_arg = c("Suomi", "Synteettinen kontrolli", "Yksi maa jätetty pois maajoukosta"))




```

# Yksityinen sektori

```{r private}
###########################
### Deploying the model ###
###########################




private_ssca <- ssca_dat %>% 
  filter(nace0 == "private") %>% 
  ssca_est(unit_var = "geo",
                 target_unit = "FI",
                 value_var = "lp_ind",
                 time_var = "time", est_periods = est_periods, eval_periods = eval_periods)
  


###############
### Results ###
###############

### Country weights ###
private_ssca$w_list$W_star

### Normalized RMSE Loss ###
comp.rmse(private_ssca$z_list, private_ssca$w_list$W_star)

#############
### Plots ###
#############



ssca_plot("Yksityinen sektori", ssca_obj = filter(ssca_lp_ind10, nace0 == "private")[["ssca_obj_08"]][[1]])


```
