---
title: "Raportin luvun 3 kuviot"
author: "Janne Huovari"
date: "`r Sys.Date()`"
output: rmarkdown::html_document

---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  fig.path = "test/",
  fig.width = 6.3,
  fig.height = 4.1,
  collapse = TRUE,
  comment = "#>", 
  echo = FALSE, 
  comment = FALSE, 
  warning = FALSE
)


library(tidyverse)
library(glue)
library(ggptt)
library(patchwork)
library(ficomp)
library(gt)
library(tidyselect)

devtools::load_all()

set_board_theme(base_size = 8)

# Data

data("data_main_groups", "data_main10_groups", "ssca10_est_results", "ssca10_est_results", "ssca_exp_est_results")
data("weights_ecfin27", "weights_ecfin37", package = "ficomp")




high_country <- "Suomi"
high_countries <- c("Ruotsi", "Euroalue-12", "Saksa", "Yhdysvallat")

plot_start_year <- 2000

```

# Työn tuottavuus



## Yksityinen sektori

```{r private, fig.height=6.3}

trip_plot(ssca_obj = ssca10_est_results, data_main10_g_weighted, nace = "private", plot_var = "lp_ind", base_year, high_country, high_countries)

ggsave(here::here("figures/private.pdf"), width = 13.5, height = 13.5, units = "cm")
ggsave(here::here("figures/private.png"), width = 13.5, height = 13.5, units = "cm")
# ggsave(here::here("figures/manu.svg"), width = 10, height = 8)
# ggsave(here::here("figures/manu.png"), width = 10, height = 8)
# ggsave(here::here("figures/manu.eps"), width = 10, height = 8)
# ggsave(here::here("figures/manu.ps"), width = 10, height = 8)
# ggsave(here::here("figures/manu.wmf"), width = 10, height = 8)

```
