---
title: "Tuottavuuden taso"
author: "Janne Huovari"
date: "`r Sys.Date()`"
output: rmarkdown::html_document

---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  fig.path = "fig_report/",
  fig.width = 10,
  fig.height = 8,
  collapse = TRUE,
  comment = "#>", 
  echo = FALSE, 
  comment = FALSE, 
  warning = FALSE
)


library(tidyverse)
library(glue)
library(ggptt)
library(patchwork)
library(ficomp)
library(gt)
library(tidyselect)

devtools::load_all()

# set_board_theme(base_size = 8)
set_board_theme(base_size = 12)

# Data

data("data_main_groups", "data_main10_groups", "synth_est_results", "synth10_est_results")
data("weights_ecfin27", "weights_ecfin37", package = "ficomp")


fig_height <- 10

high_country <- "Suomi"
high_countries <- c("Ruotsi", "Euroalue-12", "Saksa", "Yhdysvallat", "Tanska")

plot_start_year <- 2000

geo_level <- c("FI", "SE", "US", "DE", "DK", "FR", "IT", "ES") 

```


## Yksityinen sektori


```{r}




data_main10_groups_level |> 
  filter(time >= 1980) |> 
  plot_lp_level(geos = geo_level, "private")

# save_figs("Kuvio_2_1_lp_level_private", en = TRUE)

# data_main10_groups_level |> 
#   mutate(lp_level05 = lp_fp05_eur) |> 
#   filter(time >= 1980) |> 
#   plot_lp_level(geos = geo_level, "private")

```

```{r}

data_main10_groups_level |> 
  filter(time >= 1980) |> 
  plot_lp_level_rel(geos = geo_level, "private")

# save_figs("Kuvio_2_2", en = TRUE)


```

## Teollisuus

```{r}

data_main10_groups_level |> 
  filter(time >= 1995) |> 
  plot_lp_level(geos = geo_level, "manu")

last_plot()$data |> 
  select(geo, geo_name, nace0, time, lp_level05) |> 
  write.csv2(file = "~/../Downloads/lp_level05_teollisuus.csv")

save_figs("Kuvio_2_4_lp_level_manu", en = TRUE)



```

## Palvelut

```{r}

data_main10_groups_level |> 
  filter(time >= 1995) |> 
  plot_lp_level(geos = geo_level, "service")

last_plot()$data |> 
  select(geo, geo_name, nace0, time, lp_level05) |> 
  write.csv2(file = "~/../Downloads/lp_level05_palvelut.csv")

save_figs("Kuvio_2_5_lp_level_service", en = TRUE)

```

## Tuottavuuden taso - palveluiden alatoimialat

```{r, eval=FALSE}

data_main |> 
  filter(geo %in% c("SE", "FI", "DK", "US", "DE"),
         !(nace_r2 %in% c("C", "F", "C26", "TOTAL"))) |> 
  left_join(select(exh_eur_a, geo, time, exh_eur = values), by = c("geo", "time")) |>
  left_join(data_ggdc_10_go_level05, by = c("geo", "nace_r2")) |>
  mutate(lp_ind = B1G__CLV15_MNAC / EMP_DC__THS_HW) |>
  group_by(geo, nace_r2) |> 
  mutate(lp_ind = rebase(lp_ind, time, 2005),
         lp_fp05 = (B1G__CP_MNAC / EMP_DC__THS_HW)[time == 2005] * lp_ind / 100,
         lp_fp05_eur = lp_fp05 / exh_eur[time == 2005]) |>
  mutate(lp_level05 = lp_fp05_eur / go_level05) |>
  group_by(nace_r2) |> 
  mutate(lp_level05 = 100 * lp_level05 / lp_level05[geo == "US" & time == 2005]) |> 
  ungroup() |>
  mutate(nace_r2 = recode(nace_r2, G = "Kauppa", H = "Kuljetus", I = "Majoitus- ja\nravitsemistoiminta",
                          J = "Informaatio ja viestintä", M = "Ammatillinen, tieteellinen\nja tekninen toiminta",
                          N = "Hallinto- ja tukipalvelut")) |>
  mutate(geo = as_factor(recode(geo, !!!set_names(names(countries), countries)))) |>
  mutate(geo = fct_relevel(geo, "Ruotsi", "Saksa", "Suomi", "Tanska", "USA")) |>
  mutate(nace_r2 = as_factor(nace_r2)) |> 
  ggplot(aes(time, lp_level05, colour = geo)) +
  facet_wrap(~nace_r2) +
  geom_line() +
  # geom_h0() +
  scale_y_log10(breaks = seq(0, 300, 50)) +
  scale_x_continuous(labels = no_century) +
  the_legend_bot() +
  theme(strip.text.x = ggplot2::element_text(size = ggplot2::rel(0.8))) +
  the_title_blank("xl") +
  labs(y = "Indeksi, Yhdysvallat 2005 = 100, logaritminen asteikko",
       title = "Työn tuottavuuden taso",
       caption = "Lähde: Eurostat, OECD, BLS, Inklaar & Timmer (2014), Tuottavuuslautakunta")

# save_figs("Kuvio_2_6", height = fig_height + 4, en = TRUE)

```

### Hinta

```{r, eval=FALSE}

data_main |> 
  filter(geo %in% c("SE", "FI", "DK", "US", "DE"),
         !(nace_r2 %in% c("C", "F", "C26", "TOTAL"))) |> 
  left_join(select(exh_eur_a, geo, time, exh_eur = values), by = c("geo", "time")) |>
  left_join(data_ggdc_10_go_level05, by = c("geo", "nace_r2")) |>
  mutate(lp_ind = B1G__CLV15_MNAC / EMP_DC__THS_HW) |>
  group_by(geo, nace_r2) |> 
  mutate(lp_ind = rebase(lp_ind, time, 2005),
         p_ind = (B1G__CP_MNAC / B1G__CLV15_MNAC),
         p_ind_05 = rebase(p_ind, time, 2005)) |>
  ungroup() |>
  mutate(p_level05 = p_ind_05 / go_level05) |>
  mutate(nace_r2 = eurostat::label_eurostat(nace_r2, "nace_r2")) |> 
  mutate(nace_r2 = as_factor(nace_r2)) |> 
  ggplot(aes(time, p_level05, colour = geo)) +
  facet_wrap(~nace_r2, scales = "free") +
  geom_line() +
  geom_h0() +
  the_title_blank() +
  the_legend_bot()

# save_figs("level_service_price", en = TRUE)

```

### Nimellinen

```{r, eval=FALSE}

data_main |> 
  filter(geo %in% c("SE", "FI", "DK", "US", "DE"),
         !(nace_r2 %in% c("C", "F", "C26", "TOTAL"))) |> 
  left_join(select(exh_eur_a, geo, time, exh_eur = values), by = c("geo", "time")) |>
  left_join(data_ggdc_10_go_level05, by = c("geo", "nace_r2")) |>
  mutate(lp_ind = B1G__CP_MNAC / EMP_DC__THS_HW) |>
  group_by(geo, nace_r2) |> 
  mutate(lp_ind = rebase(lp_ind, time, 2005),
         lp_fp05 = (B1G__CP_MNAC / EMP_DC__THS_HW)[time == 2005] * lp_ind / 100,
         lp_fp05_eur = lp_fp05 / exh_eur[time == 2005]) |>
  ungroup() |>
  mutate(lp_level05 = lp_fp05_eur / go_level05) |>
  mutate(nace_r2 = eurostat::label_eurostat(nace_r2, "nace_r2")) |> 
  mutate(nace_r2 = as_factor(nace_r2)) |> 
  ggplot(aes(time, lp_level05, colour = geo)) +
  facet_wrap(~nace_r2, scales = "free") +
  geom_line() +
  geom_h0() +
  the_title_blank() +
  the_legend_bot()

# save_figs("level_service_cp", en = TRUE)

```
